CREATE TABLE ACCOUNT
(
    ACCOUNT_NUMBER VARCHAR(25) NOT NULL,
    BALANCE        DECIMAL     NOT NULL DEFAULT 0.00,
    VERSION        INT         NOT NULL DEFAULT 0,
    PRIMARY KEY (ACCOUNT_NUMBER)
);
