INSERT INTO ACCOUNT (ACCOUNT_NUMBER, BALANCE)
VALUES ('1', 100.00);
INSERT INTO ACCOUNT (ACCOUNT_NUMBER, BALANCE)
VALUES ('2', 100.00);
INSERT INTO ACCOUNT (ACCOUNT_NUMBER, BALANCE)
VALUES ('3', 100.00);
